project_name="amberdata"
region="europe-west2"
gcs_bucket_name = "bucket-amberdata-dev-test"
storage_class = "STANDARD"
bq_dataset_name="dataset_amberdata_dev"
spark_cluster_name="spark-amberdata-dev"
